Added setup for the page builder
justbetter/statamic-page-builder-kit pull request #1
Opened 2024-11-19 14:16 UTC by kevinmeijer97

Quick description on how this works:

After installing the project is checked for a Pages collection + blueprint. 
If they don't exist and the option for creating is enabled in the config we add the Page collection with a default Blueprint that has the Page Builder integrated.

The Components in the Page Builder are automatically added based on the name of a fieldset.
The handle of a component should look something like this: `component_{group}_{component_name}`.
This way we can still divide the components into different groups.

This way it's also possible to add new components from the base of your project or another package by simply making another fieldset with the correct name.

I've decided on generating the Pages collection like this, this way we can automatically set it up for all the registered sites.

2024-11-20 08:30 UTC, BobWez98 requested changes

2024-11-20 08:30 UTC, BobWez98 commented on resources/views/page.blade.php
> +{{--@section('title', $meta_title->raw() ? $meta_title .' - '. config('app.name') : config('app.name'))--}}
I think we should either add these in the blueprint, or remove the comments

2024-11-20 08:30 UTC, BobWez98 commented on src/ServiceProvider.php
> +
Maybe it's better here to listen to CollectionCreated maybe? It feels kind of dirty running this a lot.

2024-11-20 08:30 UTC, BobWez98 commented on src/ServiceProvider.php
> +            ->bootPageBuilder();
Maybe we can move all the code to a trait, to clean up the service provider a bit.

2024-11-20 13:19 UTC, kevinmeijer97 commented on src/ServiceProvider.php
> +
Moved this to a Command since you would only have to do this once when installing the addon.

2024-11-20 13:19 UTC, kevinmeijer97 commented on src/ServiceProvider.php
> +            ->bootPageBuilder();
Moved the registration for the pagebuilder fieldset to a trait and added caching

2024-11-20 13:20 UTC, kevinmeijer97 commented on resources/views/page.blade.php
> +{{--@section('title', $meta_title->raw() ? $meta_title .' - '. config('app.name') : config('app.name'))--}}
Forgot to remove this, this is maybe something for later

2024-11-21 12:59 UTC, royduin commented
I see English and Dutch mixed?

2024-12-18 12:19 UTC, BobWez98 commented
Is this reviewable or on hold? (can we change it to draft if it's on hold?)

2026-02-25 09:59 UTC, closed without merging